import 'package:equatable/equatable.dart';

import 'mission_type.dart';

/// Pure domain entity for the daily AI-generated mission (premium feature).
///
/// Mirrors `GET /ai-missions/today` ->
/// `{ id, missionType, difficulty, instruction, targetObject?, expiresAt }`.
class AiMission extends Equatable {
  const AiMission({
    required this.id,
    required this.missionType,
    required this.difficulty,
    required this.instruction,
    required this.expiresAt,
    this.targetObject,
  });

  final String id;
  final MissionKind? missionType;
  final MissionDifficulty difficulty;

  /// Natural-language instruction generated by the AI, e.g.
  /// "Take a photo of your toothbrush to prove you're up!".
  final String instruction;

  /// Optional target object for object-detection AI missions.
  final String? targetObject;

  /// When this mission expires (UTC). After this, the user must fetch a new one.
  final DateTime expiresAt;

  bool get isExpired => DateTime.now().toUtc().isAfter(expiresAt);

  @override
  List<Object?> get props =>
      [id, missionType, difficulty, instruction, targetObject, expiresAt];
}
